### ISSUE TITLE
出现错误

### ISSUE THREAD

**Issue by SmilingXia** [daiyangyang945/UyaliBeautyFaceSDK#1]
<img width="536" alt="截屏2023-03-20 21 14 00" src="https://user-images.githubusercontent.com/22338818/226349920-62593ec4-d130-4a57-8d04-1fd52babe554.png">

**Comment by daiyangyang945** [comment]
这个应该是美妆素材的问题，我已经删除了会出现问题的素材

**Comment by SmilingXia** [comment]
如果采集的CMSampleBufferRef mediaSubType 是 kCVPixelFormatType_32BGRA是能正常使用的，一旦我使用kCVPixelFormatType_420YpCbCr8BiPlanarFullRange就不行了。有好的解决方法吗？

**Comment by daiyangyang945** [comment]
可以把YUV渲染为BGRA，一般可以通过openGLES的shader来转换,转换公式是：
`R=Y+1.4075*(V-128)
G=Y-0.3455*(U-128) – 0.7169*(V-128)
B=Y+1.779*(U-128)`
这个应该是最快的，还有我记得Google有一个libyuv的库，你可以去了解一下，但是它的实时性应该是不如openGLES的
